### ISSUE TITLE
Only found one instance of commandQueue - what is it?

### ISSUE THREAD

**Issue by marton-demeter** [KittsSeniorDesign/DifferentialDrive#11]
We have a commandQueue in /Comm/CommBaseClass.py in line 78, I don't get what goes in it or where it's initialized

**Comment by RyanLoringCooper** [comment]
It is created in DDStarter.py. It is declared in util.py. It is consumed by MotorController.py. it is filled by an instance of CommProcess.py

**Comment by marton-demeter** [comment]
I only see controllerQueue but no commandQueue. Might be missing something.

**Comment by RyanLoringCooper** [comment]
Oh sorry that was for controllerQueue. One moment

**Comment by RyanLoringCooper** [comment]
Yeah commandQueue was old code. Good catch. I changed it to gcsDataQueue like it should be.

**Comment by marton-demeter** [comment]
Thanks!
